# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b280deb7873422fee4d50a82a5d14753315866dbb4e736486718f8f6d276454abf83cc583b591c52deb1d92b14f9fea235b317af403190b4b3113a640a379914

test:
  secret_key_base: f9e2c704687d96480f07d4568af3b9d03398385a3aba1c43c3a5433038948c85057cad3fcbd1ddd1bd18f0322af0c5ff70494aa8efaf04cbf34969916693befa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
